from scraper.web_coop_text import get_name, get_price, finished_product

def test_get_name():
    test_line = '<div class="ProductTeaser-content"><div class="ProductTeaser-media"><a aria-label="Ost Cheddar " class="u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001"><div class="ProductTeaser-image"><img alt="Ost Cheddar " draggable="false" loading="lazy" src="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_120,w_120/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg" srcset="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_240,w_240/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg 2x"/></div></a></div><div class="ProductTeaser-info"><div class="ProductTeaser-headingContainer"><p class="ProductTeaser-heading"><a class="ProductTeaser-link u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001" tabindex="-1">Ost Cheddar </a></p><div class="ProductTeaser-features"><div class="gUGSFhfR BPNK9JRC xpx_0_aF TGFfLiEs">550 gram ungefärlig vikt</div></div></div><div class="ProductTeaser-detailsContainer"><div class="ProductTeaser-details"><div class="ProductTeaser-brand"><span>Arla®.</span></div><div>Jfr-pris: 155,00 kr/kg</div></div><div class="SnZ2rtnf sJx8F6kR ProductTeaser-pricesContainer"><span class="wqjVwCAg X7I7xYL7"><span>85,25</span><span class="gD6iZrT8"> /st</span></span></div></div></div><div class="u-posRelative"><span aria-atomic="true" aria-live="polite" class="u-hiddenVisually">Denna vara är borttagen från varukorgen.</span><button aria-label="Lägg till Ost Cheddar  i varukorgen" class="Wy2NiM6K mOvy16Ff n7zzFW7b IGOfolJn" data-testid="add_to_cart_button" type="button">Köp</button></div></div>'
    result = get_name(test_line)
    assert result == "Ost Cheddar "

def test_get_price():
    test_line = '<div class="ProductTeaser-content"><div class="ProductTeaser-media"><a aria-label="Ost Cheddar " class="u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001"><div class="ProductTeaser-image"><img alt="Ost Cheddar " draggable="false" loading="lazy" src="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_120,w_120/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg" srcset="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_240,w_240/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg 2x"/></div></a></div><div class="ProductTeaser-info"><div class="ProductTeaser-headingContainer"><p class="ProductTeaser-heading"><a class="ProductTeaser-link u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001" tabindex="-1">Ost Cheddar </a></p><div class="ProductTeaser-features"><div class="gUGSFhfR BPNK9JRC xpx_0_aF TGFfLiEs">550 gram ungefärlig vikt</div></div></div><div class="ProductTeaser-detailsContainer"><div class="ProductTeaser-details"><div class="ProductTeaser-brand"><span>Arla®.</span></div><div>Jfr-pris: 155,00 kr/kg</div></div><div class="SnZ2rtnf sJx8F6kR ProductTeaser-pricesContainer"><span class="wqjVwCAg X7I7xYL7"><span>85,25</span><span class="gD6iZrT8"> /st</span></span></div></div></div><div class="u-posRelative"><span aria-atomic="true" aria-live="polite" class="u-hiddenVisually">Denna vara är borttagen från varukorgen.</span><button aria-label="Lägg till Ost Cheddar  i varukorgen" class="Wy2NiM6K mOvy16Ff n7zzFW7b IGOfolJn" data-testid="add_to_cart_button" type="button">Köp</button></div></div>'
    result = get_price(test_line)
    assert result == "85,25"

def test_finnished_product():
    test_line = '<div class="ProductTeaser-content"><div class="ProductTeaser-media"><a aria-label="Ost Cheddar " class="u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001"><div class="ProductTeaser-image"><img alt="Ost Cheddar " draggable="false" loading="lazy" src="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_120,w_120/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg" srcset="//res.cloudinary.com/coopsverige/images/f_auto,fl_clip,fl_progressive,q_auto,c_lpad,g_center,h_240,w_240/v1671188653/cloud/269659/Ost%20Cheddar%20.jpg 2x"/></div></a></div><div class="ProductTeaser-info"><div class="ProductTeaser-headingContainer"><p class="ProductTeaser-heading"><a class="ProductTeaser-link u-outlineSolidBase2" href="/handla/varor/ost/palaggsost/cheddar/ost-cheddar-2340414100001" tabindex="-1">Ost Cheddar </a></p><div class="ProductTeaser-features"><div class="gUGSFhfR BPNK9JRC xpx_0_aF TGFfLiEs">550 gram ungefärlig vikt</div></div></div><div class="ProductTeaser-detailsContainer"><div class="ProductTeaser-details"><div class="ProductTeaser-brand"><span>Arla®.</span></div><div>Jfr-pris: 155,00 kr/kg</div></div><div class="SnZ2rtnf sJx8F6kR ProductTeaser-pricesContainer"><span class="wqjVwCAg X7I7xYL7"><span>85,25</span><span class="gD6iZrT8"> /st</span></span></div></div></div><div class="u-posRelative"><span aria-atomic="true" aria-live="polite" class="u-hiddenVisually">Denna vara är borttagen från varukorgen.</span><button aria-label="Lägg till Ost Cheddar  i varukorgen" class="Wy2NiM6K mOvy16Ff n7zzFW7b IGOfolJn" data-testid="add_to_cart_button" type="button">Köp</button></div></div>'
    result = finished_product(test_line)
    assert result == {"name": "Ost Cheddar ", "price" : "85,25",  'date_added': '2025-02-08' } #change date_added to the date when you test the function

    